FROM golang:1.24-alpine

WORKDIR /app

COPY ./apps/guestbook /app/apps/sse_guestbook
COPY .air.toml.sse_guestbook /app/.air.toml
COPY ./config /app/config
COPY ./helper /app/helper
COPY go_work.sse.guestbook /app/go.work


# Set working directory to the specific service
WORKDIR /app/apps/sse_guestbook

RUN go work sync && go mod tidy

RUN go install github.com/air-verse/air@latest

WORKDIR /app

CMD ["air", "-c", ".air.toml"]
